function makeOutput(angs,outType,outPuts,outDir,imgName,inc,varargin)

% makeOutput.m
% This function creates the output of curvGUI.m.
% 
% Inputs:
% angs - vector of measured angles generated by newCurv.m
% 
% outType - scalar
% 
% outPuts - vector of 4 values indicating the type of output
% 
% outDir - location for saving output files
%     
% imgName - names for the files
%     
% Carolyn Pehlke, Laboratory for Optical and Computational Instrumentation, July 2010

outS = outType * outPuts;
bins = min(angs):inc:max(angs);
[n xout] = hist(angs,bins);
imHist = vertcat(n,xout);

for xx = 1:length(outS);

    outTest = outS(xx);
    
    switch xx
        case 1
            if nargin >= 4
                fileOut = fullfile(outDir,strcat(imgName,'_hist.csv'));
            end
            titleString = ['Histogram of Measured Angles in ',imgName];
            switch outTest
                case 0 
                    spacetaker = 1 + 1;
                    
                case 2
                    hFig = figure('Name',titleString);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(hFig,'Color',defaultBackground)
                    hist(angs,bins);
                    title(titleString)
        
                case 3
                    csvwrite(fileOut,imHist);
        
                case 5
                    csvwrite(fileOut,imHist);
                    hFig = figure('Name',titleString); 
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(hFig,'Color',defaultBackground)
                    bar(xout,n);
                    title(titleString)
            end
            
        case 2
            if nargin >= 4
                fileOut = fullfile(outDir,strcat(imgName,'_compass.csv'));
            end
            titleString = ['Compass Plot of Measured Angles in ',imgName];
            U = cosd(xout).*n;
            V = sind(xout).*n;
            comps = vertcat(U,V);
            switch outTest
                case 0
                    spacetaker = 1 + 1;
                    
                case 2
                    cFig = figure('Name',titleString);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(cFig,'Color',defaultBackground)
                    compass(U,V)
                    title(titleString)
                case 3
                    csvwrite(fileOut,comps);
                    
                case 5
                    csvwrite(fileOut,comps);
                    cFig = figure('Name',titleString);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(cFig,'Color',defaultBackground)
                    compass(U,V)
                    title(titleString)
            end
            
        case 3
            if nargin >= 4
                fileOut = fullfile(outDir,strcat(imgName,'_stats.csv'));
            end
            
            aveAngle = mean(angs);
            medAngle = median(angs);
            stdAngle = std(angs);
                       
            alignMent = 1 - (2*(stdAngle/90));
            
            switch outTest
                case 0
                    spacetaker = 1 + 1;
                    
                case 2
                    textFig = figure('Name',['Angle Statistics for ',imgName],'Position',[200 400 450 150]);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(textFig,'Color',defaultBackground)
                    set(gca,'Visible','off')
                    textPanel = uipanel(textFig,'Units','normalized','Position',[.1 .1 .8 .8]);
                    uicontrol(textPanel,'Style','text','String',['Mean Angle: ',num2str(aveAngle,'%6.2f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .7 .8 .2]);
                    uicontrol(textPanel,'Style','text','String',['Median Angle: ',num2str(medAngle,'%6.2f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .5 .8 .2]);
                    uicontrol(textPanel,'Style','text','String',['Standard Deviation: ',num2str(stdAngle,'%6.2f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .3 .8 .2]);
                    uicontrol(textPanel,'Style','text','String',['Coefficient of Alignment: ',num2str(alignMent,'%6.4f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .1 .8 .2]);                  
                    
                case 3
                    stats = vertcat(aveAngle,medAngle,stdAngle,alignMent);
                    csvwrite(fileOut,stats);
                    
                case 5
                    stats = vertcat(aveAngle,medAngle,stdAngle,alignMent);
                    csvwrite(fileOut,stats);
                    textFig = figure('Name',['Angle Statistics for ',imgName],'Position',[200 400 450 150]);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(gca,'Visible','off')
                    set(textFig,'Color',defaultBackground)
                    textPanel = uipanel(textFig,'Units','normalized','Position',[.1 .1 .8 .8]);
                    uicontrol(textPanel,'Style','text','String',['Mean Angle: ',num2str(aveAngle,'%6.2f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .7 .8 .2]);
                    uicontrol(textPanel,'Style','text','String',['Median Angle: ',num2str(medAngle,'%6.2f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .5 .8 .2]);
                    uicontrol(textPanel,'Style','text','String',['Standard Deviation: ',num2str(stdAngle,'%6.2f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .3 .8 .2]);
                    uicontrol(textPanel,'Style','text','String',['Coefficient of Alignment: ',num2str(alignMent,'%6.4f')],'Units','normalized','FontName','FixedWidth','Position',[.1 .1 .8 .2]); 

            end
            
        case 4
            if nargin >= 4
                fileOut = fullfile(outDir,strcat(imgName,'_values.csv'));
            end
                angs2 = {angs};
            
            switch outTest
                case 0
                    spacetaker = 1 + 1;
                case 2
                    tableFig = figure('Name',['Measured Angles in ',imgName],'Position',[400 200 100 300]);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(tableFig,'Color',defaultBackground)
                    tabl = uicontrol('Parent',tableFig,'Style','listbox','String',angs2,'Visible','off','Units','normalized','Position',[.1 .1 .8 .8]);
                    set(tabl,'Visible','on')
                    
                case 3
                    csvwrite(fileOut,angs);
                    
                case 5
                    tableFig = figure('Name',['Measured Angles in ',imgName],'Position',[400 200 100 300]);
                    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
                    set(tableFig,'Color',defaultBackground)
                    tabl = uicontrol('Parent',tableFig,'Style','listbox','String',angs2,'Visible','off','Units','normalized','Position',[.1 .1 .8 .8]);
                    set(tabl,'Visible','on')
                    csvwrite(fileOut,angs);
            end
    end
end

end
