function writeAllHistData(histData, NorT, outDir, checkFirst, stats, imgName, sliceNum)

% writeAllHistData.m - writes histogram data out for a batch processed group of files. 
%   This was created to fulfill a specific need of the Keely lab.
% 
% Inputs:
%   histData - list of binned data generated by the process image function
%   NorT - Normal or tumor flag
%   outDir - text indicating the directory to write the output file
%   checkFirst - if this is the first file after starting the program,
%       restart a new output file
%   stats - structure of stats data generated by the stats function
%   imgName - name of the current image being processed
%   sliceNum - the z section number in a stack
%
% Output:
%   tab delimited text file
%
%
% By Jeremy Bredfeldt, LOCI, Morgridge Institute for Research, 2013


    if checkFirst == 1
        %if it's the first file after starting the program, start a new output file
        fid = fopen([outDir 'AllHistData.txt'],'w+');
    else
        %append the current file
        fid = fopen([outDir 'AllHistData.txt'],'a+');
    end
    
    if isempty(histData)
        fprintf(fid,'%s\t%d\t%.2f\t%d\t%s\t',imgName,sliceNum,0,0,NorT);
        fprintf(fid,'\r\n');        
    else
        %for ii = 1:size(histData,1)
        for ii = 1:1
            fprintf(fid,'%s\t%d\t%.2f\t%d\t%s\t',imgName,sliceNum,histData(ii,1),histData(ii,2),NorT);
            if ii == 1
                for jj = 1:size(stats)
                    fprintf(fid,'%0.4f\t',stats(jj));
                end
            end
            fprintf(fid,'\r\n');
        end
    end
    fclose(fid);
end