
function featureNames = formatFeatureName(FeatureControlParameters)
% Format the feature names for curvealign visualization
% Input:  
%      FeatureControlParameters.minimumNearestFibers
%      FeatureControlParameters.minimumBoxSize
% Output:
%      featureNames: formatted feature names for visualization module
featureNames ={
    '01-FiberKeyToCTFIRE'; ...
    '02-End Point Row'; ...
    '03-End Point Column'; ...
    '04-Fiber Absolute Angle'; ...
    '05-Fiber Weight'; ...
    '06-Total Length'; ...
    '07-End2End Length'; ...
    '08-Curvature'; ...
    '09-Width'; ...
    sprintf('10-DistanceToNearest %d',2^0*FeatureControlParameters.minimumNearestFibers); ...
    sprintf('11-DistanceToNearest %d',2^1*FeatureControlParameters.minimumNearestFibers); ...
    sprintf('12-DistanceToNearest %d',2^2*FeatureControlParameters.minimumNearestFibers); ...
    sprintf('13-DistanceToNearest %d',2^3*FeatureControlParameters.minimumNearestFibers); ...
    '14-Mean Nearest Distance'; ...
    '15-Std Nearest Distance'; ...
    sprintf('16-Box Density %d',2^0*FeatureControlParameters.minimumBoxSize); ...
    sprintf('17-Box Density %d',2^1*FeatureControlParameters.minimumBoxSize); ...
    sprintf('18-Box Density %d',2^2*FeatureControlParameters.minimumBoxSize); ...
    sprintf('19-AlignmentOfNearest %d',2^0*FeatureControlParameters.minimumNearestFibers); ...
    sprintf('20-AlignmentOfNearest %d',2^1*FeatureControlParameters.minimumNearestFibers); ...
    sprintf('21-AlignmentOfNearest %d',2^2*FeatureControlParameters.minimumNearestFibers); ...
    sprintf('22-AlignmentOfNearest %d',2^3*FeatureControlParameters.minimumNearestFibers); ...
    '23-Mean Nearest Alignment'; ...
    '24-Std Nearest Alignment'; ...
    sprintf('25-Box Alignment %d',2^0*FeatureControlParameters.minimumBoxSize); ...
    sprintf('26-Box Alignment %d',2^1*FeatureControlParameters.minimumBoxSize); ...
    sprintf('27-Box Alignment %d',2^2*FeatureControlParameters.minimumBoxSize); ...
    '28-NearestDistanceToBoundary'; ...
    '29-Inside Boundary Flag'; ...
    '30-Nearest Relative Angle'; ...
    '31-Extension Point Distance'; ...
    '32-Extension Point Angle'; ...
    '33-Boundary Point Row'; ...
    '34-Boundary Point Column'
    };

return
